name: DeathLogger
version: '2.1'
main: cc.synkdev.deathLogger.DeathLogger
api-version: '1.19'
authors: [ Synk ]
commands:
  getdeath:
    usage: "/getdeath"
  lastdeaths:
    usage: "/lastdeaths"
  dlreload:
    usage: "/dlreload"

