name: DeathLogger
version: '2.4'
main: cc.synkdev.deathLogger.DeathLogger
api-version: '1.13'
authors: [ Synk ]
commands:
  getdeath:
    usage: "/getdeath"
  lastdeaths:
    usage: "/lastdeaths"
  dl:
    usage: "/dl"

